version: "3.9"

volumes:
  redis-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR_PATH_HOST}/redis/data
  postgres-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR_PATH_HOST}/postgres/data

secrets:
  # echo ${POSTGRES_USER} | docker secret create postgres-root-user -
  postgres-root-user:
    file: ./postgres/secrets/root_user.txt
  # echo ${POSTGRES_PASSWORD} | docker secret create postgres-root-password -
  postgres-root-password:
    file: ./postgres/secrets/root_password.txt

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-db:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 20s
      timeout: 5s
      retries: 5

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    secrets:
      - postgres-root-user
      - postgres-root-password
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 20s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    image: crccheck/hello-world
    ports:
      - 8000:8000

  # step 2: docker compose up -d frontend nginx
  # step 6: docker compose up -d nginx
  nginx:
    container_name: nginx
    depends_on:
      - frontend
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: ${HOST_DOMAIN}
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 8000
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  # step 3: docker compose up -d certbot
  # step 4: docker logs certbot
  # step 7: crontab -e
  # step 8: 0 5 1 */2 * /usr/bin/docker compose -f ${DIR_PATH_HOST}/docker-compose.yml up certbot
  certbot:
    container_name: certbot
    depends_on:
      - nginx
    image: certbot/certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${HOST_CERTBOT_EMAIL} -d ${HOST_DOMAIN} --agree-tos
